# Generated by Django 4.1.2 on 2022-10-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_equipamentos', '0004_rename_observacoesequipamentos_obsequipamentos'),
        ('manobras', '0001_initial'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentos',
            name='manobras',
            field=models.ManyToManyField(to='manobras.manobras'),
        ),
        migrations.AddField(
            model_name='equipamentos',
            name='observacoes',
            field=models.ManyToManyField(to='obs_equipamentos.obsequipamentos'),
        ),
    ]
