# Generated by Django 4.1.2 on 2022-10-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subestacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt', models.IntegerField()),
                ('subestacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subestacoes.subestacoes')),
            ],
        ),
    ]
