# Generated by Django 4.1.2 on 2022-10-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subestacoes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servico',
            new_name='Servicos',
        ),
    ]
