# Generated by Django 4.1.2 on 2022-10-24 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('obs_equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacoesequipamentos',
            name='equipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='equipamentos.equipamentos'),
            preserve_default=False,
        ),
    ]
