# Generated by Django 4.1.2 on 2022-10-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_equipamentos', '0002_observacoesequipamentos_equipamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacoesequipamentos',
            name='equipamento',
        ),
        migrations.AlterField(
            model_name='observacoesequipamentos',
            name='observacoes',
            field=models.CharField(max_length=100),
        ),
    ]
