# Generated by Django 4.1.2 on 2022-10-24 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obs_equipamentos', '0003_remove_observacoesequipamentos_equipamento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObservacoesEquipamentos',
            new_name='ObsEquipamentos',
        ),
    ]
