# Generated by Django 4.1.2 on 2022-10-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_rename_endereco_enderecos'),
        ('equipamentos', '0001_initial'),
        ('subestacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subestacoes',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enderecos.enderecos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subestacoes',
            name='equipamento',
            field=models.ManyToManyField(to='equipamentos.equipamentos'),
        ),
    ]
