# Generated by Django 4.1.2 on 2022-10-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=25)),
                ('pais', models.CharField(max_length=25)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('lontitude', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
            ],
        ),
    ]
